In [1]:
# theoritical questions

Sure, I'd be happy to explain the concepts you've mentioned:

## Data Structures in TensorFlow

TensorFlow is built around a data structure called a **tensor**. Tensors are similar to multi-dimensional arrays and are used to represent data in TensorFlow computations. There are different types of tensors, including:

1. **Constant Tensors**: Tensors with fixed values that cannot be changed after initialization.
2. **Variable Tensors**: Tensors whose values can be changed during training.
3. **Placeholder Tensors**: Tensors used as input to a computation, commonly used in older versions of TensorFlow.

## TensorFlow Constant vs. Variable

**Constant**: A TensorFlow constant is a type of tensor with a fixed value that remains constant throughout the computation. Once defined, its value cannot be changed. Constants are typically used to store model parameters or fixed data.

Example of a constant:
```python
import tensorflow as tf
a = tf.constant(5)
b = tf.constant(10)
c = a + b  # This creates a computation graph but doesn't perform the actual addition yet
```

**Variable**: A TensorFlow variable is a type of tensor that can be modified during training using optimization algorithms. Variables are commonly used to store weights and biases in neural networks that need to be updated during training.

Example of a variable:
```python
import tensorflow as tf
initial_value = tf.random.normal(shape=(3, 3), mean=0, stddev=1)
weights = tf.Variable(initial_value)
```

## Matrix Operations in TensorFlow

**Matrix Addition**: In TensorFlow, matrix addition is performed using the `tf.add()` function or the `+` operator. Example:
```python
import tensorflow as tf
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
C = tf.add(A, B)  # Alternatively: C = A + B
```

**Matrix Multiplication**: Matrix multiplication can be done using the `tf.matmul()` function or the `@` operator. Make sure the inner dimensions match for multiplication to be valid.
```python
import tensorflow as tf
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
C = tf.matmul(A, B)  # Alternatively: C = A @ B
```

**Element-wise Operations**: Element-wise operations apply a function to each element of the tensors independently. Common examples include addition, subtraction, multiplication, and division.
```python
import tensorflow as tf
A = tf.constant([1, 2, 3])
B = tf.constant([4, 5, 6])
C = tf.add(A, B)  # Element-wise addition
```

These examples illustrate the basic concepts of data structures, constants vs. variables, and common matrix operations in TensorFlow.

In [2]:
# practical implementation 

In [3]:
# task 1

In [4]:
import tensorflow as tf

# Create a normal matrix A with dimensions 2x2
A = tf.random.normal(shape=(2, 2))
print("Matrix A:")
print(A.numpy())

# Create a Gaussian matrix B with dimensions 2x2
B = tf.random.truncated_normal(shape=(2, 2))
print("\nMatrix B:")
print(B.numpy())

# Create a matrix C with dimensions 2x2 from a normal distribution with mean 2 and std dev 0.5
mean = 2
stddev = 0.5
C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print("\nMatrix C:")
print(C.numpy())

# Perform matrix addition between matrix A and matrix B
D = tf.add(A, B)
print("\nMatrix D (A + B):")
print(D.numpy())

# Perform matrix multiplication between matrix C and matrix D
E = tf.matmul(C, D)
print("\nMatrix E (C * D):")
print(E.numpy())


2023-08-16 19:46:55.928344: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 19:46:57.535717: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-16 19:46:57.537119: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-16 19:47:01.666067: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Matrix A:
[[-2.026361   -0.47975898]
 [ 1.2051065  -0.29021922]]

Matrix B:
[[ 0.09797464 -0.21872574]
 [ 0.57157093 -0.12277358]]

Matrix C:
[[2.125683  1.3919027]
 [2.6473565 1.883707 ]]

Matrix D (A + B):
[[-1.9283863 -0.6984847]
 [ 1.7766774 -0.4129928]]

Matrix E (C * D):
[[-1.6261762 -2.059603 ]
 [-1.7583863 -2.6270955]]


In [5]:
# task 2

In [6]:
import tensorflow as tf

# Create a matrix F with dimensions 2x2 using random_uniform function
F = tf.random.uniform(shape=(2, 2))
print("Matrix F:")
print(F.numpy())

# Calculate the transpose of matrix F and store the result in matrix G
G = tf.transpose(F)
print("\nMatrix G (Transpose of F):")
print(G.numpy())

# Calculate the element-wise exponential of matrix F and store the result in matrix H
H = tf.exp(F)
print("\nMatrix H (Element-wise Exponential of F):")
print(H.numpy())

# Create a matrix I by concatenating matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)
print("\nMatrix I (Concatenation of F and G horizontally):")
print(I.numpy())

# Create a matrix J by concatenating matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)
print("\nMatrix J (Concatenation of F and H vertically):")
print(J.numpy())


Matrix F:
[[0.4521197  0.3383037 ]
 [0.13002741 0.8444817 ]]

Matrix G (Transpose of F):
[[0.4521197  0.13002741]
 [0.3383037  0.8444817 ]]

Matrix H (Element-wise Exponential of F):
[[1.5716401 1.4025664]
 [1.1388596 2.3267715]]

Matrix I (Concatenation of F and G horizontally):
[[0.4521197  0.3383037  0.4521197  0.13002741]
 [0.13002741 0.8444817  0.3383037  0.8444817 ]]

Matrix J (Concatenation of F and H vertically):
[[0.4521197  0.3383037 ]
 [0.13002741 0.8444817 ]
 [1.5716401  1.4025664 ]
 [1.1388596  2.3267715 ]]
